# Generated by Django 4.1.3 on 2022-11-07 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("c_admin", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="timestamp",
            new_name="created_at",
        ),
    ]
