# Generated by Django 4.0 on 2023-03-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_admin', '0005_account_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('col_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('value', models.TextField()),
            ],
        ),
    ]
