# Generated by Django 4.1.3 on 2022-11-07 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("c_admin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Execution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(default="500", max_length=3)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("address", models.CharField(max_length=255, null=True)),
                ("city", models.CharField(max_length=50, null=True)),
                ("state", models.CharField(max_length=50, null=True)),
                ("country", models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("artist", models.CharField(max_length=255, null=True)),
                ("opener", models.CharField(max_length=255, null=True)),
                ("host", models.CharField(max_length=255, null=True)),
                ("promoter", models.CharField(max_length=255, null=True)),
                ("offering", models.CharField(max_length=255, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("price", models.FloatField(default=0.0)),
                ("ticket_link", models.CharField(max_length=255, null=True)),
                ("is_age_restricted", models.BooleanField(default=False)),
                ("orig_link", models.CharField(max_length=255, null=True)),
                ("orig_thumb", models.CharField(max_length=255, null=True)),
                (
                    "exec",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event.execution",
                    ),
                ),
                (
                    "poster",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="c_admin.account",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event.venue",
                    ),
                ),
            ],
        ),
    ]
