# Generated by Django 4.2.17 on 2024-12-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='age_barrier',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='genres',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_event',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='late',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='link_in_bio',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='num_events',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='rsvp_required',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='FavoritesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=255)),
                ('events', models.ManyToManyField(blank=True, related_name='favorites', to='event.event')),
            ],
        ),
    ]
