# Generated by Django 4.1.3 on 2022-12-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("c_admin", "0003_logs"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="created_by",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
