# Generated by Django 4.2.17 on 2024-12-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_admin', '0006_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=255, null=True)),
                ('last_run', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='logs',
            old_name='number_of_accounts',
            new_name='number_of_new_events',
        ),
        migrations.RemoveField(
            model_name='logs',
            name='number_of_new_images',
        ),
        migrations.AddField(
            model_name='logs',
            name='accounts_list',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='logs',
            name='execution_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='logs',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='logs',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
