# Generated by Django 4.1.3 on 2022-11-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("c_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
