# Generated by Django 4.1.3 on 2022-12-29 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("c_admin", "0004_account_created_by"),
        ("event", "0002_alter_event_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="exec",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="event.execution",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="is_age_restricted",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="poster",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="c_admin.account",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="venue",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="event.venue",
            ),
        ),
    ]
