# Generated by Django 4.2.16 on 2026-08-16 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0008_event_forlocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="canonical",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="variants",
                to="event.event",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="shortcode",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="source_key",
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="event",
            name="source_slide_index",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="suppressed",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name="EventMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(help_text="0-100 fused similarity score")),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("exact_link", "Identical source link"),
                            ("fuzzy", "Fuzzy text match"),
                            ("phash", "Perceptual image hash"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("confirmed", "Confirmed duplicate"),
                            ("rejected", "Not a duplicate"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_a",
                        to="event.event",
                    ),
                ),
                (
                    "event_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_b",
                        to="event.event",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "-score"],
                        name="event_event_status_21be5c_idx",
                    )
                ],
                "unique_together": {("event_a", "event_b")},
            },
        ),
    ]
