# Generated by Django 4.2.16 on 2026-09-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0010_backfill_shortcode"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["start_date"], name="event_start_date_idx"),
        ),
    ]
