export const LOGIN_SUCCESS = 'APP/AUTH/LOGIN_SUCCESS';
export const LOGIN_FAIL = 'APP/AUTH/LOGIN_FAIL';
export const REGISTER_SUCCESS = 'APP/AUTH/REGISTER_SUCCESS';
export const REGISTER_FAIL = 'APP/AUTH/REGISTER_FAIL';
export const LOGOUT = 'APP/AUTH/LOGOUT_USER';

export const SET_MESSAGE = 'APP/MESSAGE/SET_MESSAGE';
export const CLEAR_MESSAGE = 'APP/MESSAGE/CLEAR_MESSAGE';

export const LOADED_EVENT = 'APP/EVENT';
export const LOADED_EVENTS_BY_USER = 'APP/EVENTS/USER';
export const LOADED_EVENTS_BY_DATE = 'APP/EVENTS/DATE';
export const LOADED_EVENTS_BY_DATE_RANGE = 'APP/EVENTS/DATE/RANGE';
export const LOAD_FAIL = 'APP/EVENT/LOAD_FAIL';

export const SHOW_IMAGE = 'APP/EVENT/IMAGE/SHOW';
export const HIDE_IMAGE = 'APP/EVENT/IMAGE/HIDE';

export const SHOW_MAP = 'APP/EVENT/MAP/SHOW';
export const HIDE_MAP = 'APP/EVENT/MAP/HIDE';

export const SHOW_FEEDBACK_DIALOG = 'APP/EVENT/FEEDBACK/SHOW';
export const HIDE_FEEDBACK_DIALOG = 'APP/EVENT/FEEDBACK/HIDE';

export const SHOW_EVENT = 'APP/EVENT/SHOW';
export const HIDE_EVENT = 'APP/EVENT/HIDE';

export const SHOW_POPUP = 'APP/POPUP/SHOW';
export const CLOSE_POPUP = 'APP/POPUP/CLOSE';

export const SHOW_FILTER_RESULTS = 'APP/FILTER/SHOW';
export const UPDATE_FILTER = 'APP/FILTER/UPDATE';
export const RESET_FILTERS = 'APP/FILTER/RESET';
export const LOADED_EVENTS_BY_FILTER = 'APP/FILTER/RESULTS';

export const SET_SELECTED_ACCOUNTS = 'APP/ACCOUNTS/SELECTIONS';
export const SET_SELECTED_EVENTS = 'APP/EVENTS/SELECTIONS';
export const RESET_SELECTIONS = 'APP/SELECTIONS/RESET';
export const ADD_TO_DELETED_STACK = 'APP/DELETED/STACK'

export const SET_HIDDEN_COLUMNS = 'APP/EVENTS/HIDDEN_COLUMNS';
export const RESET_HIDDEN_COLUMNS = 'APP/EVENTS/RESET_COLUMN_VISIBILITY';

export const SHOW_LOADING_DIALOAG = 'APP/LOADER/SHOW';
export const HIDE_LOADING_DIALOAG = 'APP/LOADER/HIDE';
export const SHOW_SPINNER = 'APP/LOADER/SHOW_SPINNER';
export const HIDE_SPINNER = 'APP/LOADER/HIDE_SPINNER';

export const SHOW_ACTION_DIALOG = 'APP/ACTION_DIALOG/SHOW';
export const HIDE_ACTION_DIALOG = 'APP/ACTION_DIALOG/HIDE';

export const SHOW_SEARCH_RESULTS = 'APP/SEARCH/SHOW';
export const RESET_SEARCH = 'APP/SEARCH/RESET';
export const LOADED_EVENTS_BY_SEARCH = 'APP/SEARCH/EVENTS/RESULTS';
export const LOADED_ACCOUNTS_BY_SEARCH = 'APP/SEARCH/ACCOUNTS/RESULTS';

export const ADD_ACCOUNTS = 'APP/EXPERIMENTAL/ADD_ACCOUNTS';
export const CLEAR_ACCOUNTS = 'APP/EXPERIMENTAL/CLEAR_ACCOUNTS';

export const SHOW_INFO_OVERLAY = 'SHOW_INFO_OVERLAY';
export const HIDE_INFO_OVERLAY = 'HIDE_INFO_OVERLAY';

export const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS';


export const USER_LOGIN_SUCCESS = 'APP/AUTH/USER/LOGIN_SUCCESS';
export const USER_LOGIN_SUCCESS_ES = 'APP/AUTH/USER/LOGIN_SUCCESS_ES';
export const USER_LOGIN_FAIL = 'APP/AUTH/USER/LOGIN_FAIL';
export const USER_REGISTER_SUCCESS = 'APP/AUTH/USER/REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'APP/AUTH/USER/REGISTER_FAIL';
export const USER_LOGOUT = 'APP/AUTH/USER/LOGOUT_USER';

export const USER_FAVORITE_EVENT = 'APP/USER/FAVORITE_EVENT';

export const GET_ALL_USERS = 'APP/AUTH/GET_ALL_USERS';
export const EDIT_USER = 'APP/AUTH/EDIT_USER';
