# Generated by Django 4.1.3 on 2022-11-07 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("c_auth", "0002_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
