# Generated by Django 4.1.3 on 2022-12-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("c_admin", "0002_rename_timestamp_account_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Logs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scraped_at", models.CharField(max_length=255, null=True)),
                ("scraped_by", models.CharField(max_length=255, null=True)),
                ("number_of_new_images", models.IntegerField(null=True)),
                ("number_of_accounts", models.IntegerField(null=True)),
            ],
        ),
    ]
