# Generated by Django 4.1.3 on 2022-12-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("c_admin", "0004_account_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="status",
            field=models.CharField(default="Tracking", max_length=255, null=True),
        ),
    ]
